name: github pr 
on:
  pull_request:
    branches:
      - main
jobs:
  # name of the job created
  build:
    # specifies the particular OS on which this job will run
    runs-on: ubuntu-latest
    # list of steps executed in this job
    steps:
      # checks-out current repo so the job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # setup java environment for execution
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      # run unit test using maven commands
      - name: Build with Maven
        run: |
             mvn -B package --file spring-boot-first-web-application/pom.xml
             mkdir target && cp spring-boot-first-web-application/target/*.jar target

      # configure AWS keys
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.MY_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.MY_SECRET_KEY}}
          aws-region: us-east-1
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ./packer/aws-ami.pkr.hcl
      # init packer packages
      - name: Init Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ./packer/aws-ami.pkr.hcl
     # build artifact
      # - name: Build Artifact
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: build
      #     arguments: "-color=false -on-error=abort"
      #     target: ./packer/aws-ami.pkr.hcl
      #   env:
      #     PACKER_LOG: 1
      #     GITHUB_REPO_PATH: ${{ github.workspace }}
